# Generated by Django 4.2.10 on 2024-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='uguigi', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
